version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-management-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    networks:
      - school-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: school-management-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - school-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: school-management-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: school_management
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: school_user
      MYSQL_PASSWORD: school_password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - school-network

  redis:
    image: redis:alpine
    container_name: school-management-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - school-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-management-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - school-network
    depends_on:
      - db
      - redis
    command: php artisan queue:work --verbose --tries=3 --timeout=90

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-management-scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - school-network
    depends_on:
      - db
      - redis
    command: php artisan schedule:work

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  school-network:
    driver: bridge
